apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
  labels: { app: iris-api }
spec:
  replicas: 2
  selector:
    matchLabels: { app: iris-api }
  template:
    metadata:
      labels: { app: iris-api }
    spec:
      containers:
      - name: iris-api
        image: REPLACE_WITH_IMAGE                # CI will substitute this
        ports:
        - containerPort: 8000
